### PR TITLE
Update Security Scanning

### PR DESCRIPTION
**Pull request by tsande16**
Non-archived repositories should have secret_scanning enabled.

### CODE REVIEW

**Comment by tsande16** [comment]
I cannot add any reviewers. Please add @bbranan as a reviewer to this PR.

**Comment by netomi** [comment]
I removed the lines

- secret_scanning: "enabled"
- secret_scanning_push_protection: "enabled"

as they are redundant. Its already defined like that in the default, so if you dont specify it, a repo will inherit this setting.
That allows to more easily see where the setting is still disabled.

There are still a bunch of repo where it is disabled, but its a start.

**Comment by tsande16** [comment]
@netomi Thanks for the extra cleanup and info about the defaults on security scanning! 

We decided to not enable scanning on the archived repositories. Should we have that enabled on them as well? @bbranan What are your thoughts on this?

**Comment by netomi** [comment]
oh I missed that most of the repos are archived, so its perfectly fine to leave this setting as is for them as it will not have an effect.

btw. you can also take a look at the dashboard of your project here: https://otterdog.eclipse.org/projects/technology.pass

so if Bill approves, I will merge the PR. Ty

**Comment by bbranan** [comment]
@netomi We've requested moving the archived repos elsewhere in the past to make on-going management easier and also make it easier for project contributors to understand which code is active, but that request was not approved. If you have thoughts on how we might clean up the set of project repos, we'd welcome suggestions. Regardless, this change looks good.

**Review by bbranan — APPROVED** [review]

**Comment by netomi** [comment]
I looked up the related HelpDesk ticket at https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4007 and I did not read from the conversation that the request was rejected in general. The idea of a separate organization that is under the control of the JHU is something that will not work, but moving the archived repos to a separate organization under the control of the EF would work and has also been done at other occasions. If you only have a handful of repos, this might not acceptable as Fred Gurr pointed out but your case is different as you have now lots of archived repos, so I would reopen the ticket and discuss acceptable options. 

Also, if a repo is transferred to another org, GitHub will also automatically redirect requests to the old URL to the new one, so people would still easily find the content.

**Review by netomi — APPROVED** [review]

**Pull request merged**
